### ISSUE TITLE
I only get posts for community/channel url, not the community info

### ISSUE THREAD

**Issue by zpelechova** [gustavotr/reddit-scraper#40]
https://www.reddit.com/r/Minecraft/top/ - I only get posts, not infro from https://www.reddit.com/r/Minecraft/ - I also dont get any info in th edataset, what the input was (what I am trying to scrape)
https://my.apify.com/view/runs/F3NbMkgDmeVbrPW2l

**Comment by gustavotr** [comment]
"maxItems" is set to 3 in here also.
