### ISSUE TITLE
incorrect post date, I think it takes actuall date (now) instead.

### ISSUE THREAD

**Issue by zpelechova** [gustavotr/reddit-scraper#46]
The post result. https://my.apify.com/view/runs/AH3FS0yT5SIoC7TPG

**Comment by gustavotr** [comment]
I was not able to load this link, can you send me the INPUT that you used?

**Comment by zpelechova** [comment]
![image](https://user-images.githubusercontent.com/39551460/111458761-1d92ee00-871a-11eb-8760-24187befff0b.png)
https://my.apify.com/view/runs/li8IKffYuCk5NiZKA better?
